version: "3.9"
services:
  Knab.Exchange.service:
      image: ${DOCKER_REGISTRY-}exchange
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
      ports:
        - "5001:5001"
        - "5000:5000"
      volumes:
        - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
        - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      env_file: .env
      build:
        context: './'
        dockerfile: API/02.Services/KnabExchange/Knab.Exchange.Endpoint/Dockerfile

  Knab.Exchange.UI:
          image: ${DOCKER_REGISTRY-}ui
          ports:
            - "3000:3000"
          env_file: .env
          build:
            context: './UI'
            dockerfile: ./Dockerfile